version: '3.3'
services:
  libx-backend:
    build: ./back-end
    ports:
      - 8000:80
    volumes:
      - ./back-end:/usr/share/nginx/html
    restart: always
    depends_on:
      - db
    networks:
      - docker
  
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: libx_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./back-end/.docker/dbdata:/var/lib/mysql
    networks:
      - docker
  
  libx-frontend:
    build: ./front-end
    volumes:
      - ./front-end:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: ['yarn', 'serve']
    networks:
      - docker

networks:
  docker:
    driver: bridge
    
